# Generated by Django 5.2.1 on 2025-05-19 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_year", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        max_length=512, verbose_name="genre(s) of the game"
                    ),
                ),
                ("developer", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("story_length", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "full_length",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="time to 100%"
                    ),
                ),
                (
                    "meta_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="metacritic score"
                    ),
                ),
                ("average_rating", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "platforms",
                    models.CharField(
                        max_length=512,
                        verbose_name="platforms the game can be played on",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BacklogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateField(auto_now_add=True)),
                (
                    "excitement_level",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="excitement to play game",
                    ),
                ),
                ("start_date", models.DateField()),
                ("hours_played", models.PositiveIntegerField()),
                ("did_finish", models.BooleanField()),
                (
                    "end_date",
                    models.DateField(
                        verbose_name="date user finished or dropped the game"
                    ),
                ),
                ("interval_of_play", models.DurationField()),
                (
                    "user_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="user rating of the game post-completion",
                    ),
                ),
                ("was_worth_time", models.BooleanField()),
                (
                    "reflection",
                    models.TextField(
                        max_length=2048, verbose_name="user's post-game reflection"
                    ),
                ),
                (
                    "owning_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="herolog_ui.game",
                    ),
                ),
            ],
        ),
    ]
